version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=nearby-service
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nearby-service
    ports:
      - 127.0.0.1:54320:5432
  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgresql://nearby-service:postgres@postgres/nearby-service
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=myadminsecretkey
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
