version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=nearby-service
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nearby-service
    ports:
      - 127.0.0.1:54320:5432
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
